import { Rabbit, BreedingRecord, KindlingRecord, HealthRecord, VaccinationRecord, FeedingRecord, ExpenseRecord, InventoryItem, SaleRecord, FarmNotification } from '../types';

export function getSampleRabbits(farmId: string): Omit<Rabbit, 'id'>[] {
  return [
    {
      farmId,
      rabbitId: 'RT-101',
      earTag: 'ET-101',
      name: 'Thunderbolt',
      gender: 'male',
      breed: 'New Zealand White',
      color: 'Pure White (Ruby Eyed)',
      dateOfBirth: '2024-03-15',
      weight: 4.8,
      status: 'Active',
      cageNumber: 'Buck-01',
      farmSection: 'Breeder Section A',
      purchaseDate: '2024-06-01',
      purchaseCost: 45,
      source: 'Highland Rabbitry',
      photoUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&auto=format&fit=crop&q=80',
      notes: 'Proven prime stud buck. High vigor, calm temperament, excellent muscle conformation.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-102',
      earTag: 'ET-102',
      name: 'Bella Luna',
      gender: 'female',
      breed: 'Californian',
      color: 'White with Dark Points',
      dateOfBirth: '2024-04-10',
      weight: 4.2,
      status: 'Pregnant',
      cageNumber: 'Doe-03',
      farmSection: 'Maternity Row 1',
      purchaseDate: '2024-07-15',
      purchaseCost: 40,
      source: 'Valley Farm Stock',
      photoUrl: 'https://images.unsplash.com/photo-1591382696684-38c427c7547a?w=500&auto=format&fit=crop&q=80',
      notes: 'Bred to Thunderbolt on Sept 10. Due soon. Very attentive mother with past litter of 8.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-103',
      earTag: 'ET-103',
      name: 'Hazelnut',
      gender: 'female',
      breed: 'Flemish Giant',
      color: 'Sandy Brown / Fawn',
      dateOfBirth: '2024-01-20',
      weight: 6.9,
      status: 'Active',
      cageNumber: 'Doe-05',
      farmSection: 'Giant Pen B',
      purchaseDate: '2024-05-10',
      purchaseCost: 75,
      source: 'Premier Giant Breeders',
      photoUrl: 'https://images.unsplash.com/photo-1518796745738-41048802f99a?w=500&auto=format&fit=crop&q=80',
      notes: 'Heavy breeder doe with calm demeanor. Produces rapid-growing, hardy kits.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-104',
      earTag: 'ET-104',
      name: 'Shadow',
      gender: 'male',
      breed: 'Chinchilla',
      color: 'Agouti Gray Silver',
      dateOfBirth: '2024-05-02',
      weight: 4.1,
      status: 'Active',
      cageNumber: 'Buck-02',
      farmSection: 'Breeder Section A',
      purchaseDate: '2024-08-01',
      purchaseCost: 50,
      source: 'Silver Meadow Rabbitry',
      photoUrl: 'https://images.unsplash.com/photo-1535241749838-299277b6305f?w=500&auto=format&fit=crop&q=80',
      notes: 'High dense pelt and great genetic diversity. Good for cross-breeding meat lines.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-105',
      earTag: 'ET-105',
      name: 'Clover',
      gender: 'female',
      breed: 'Rex',
      color: 'Castor Velveteen',
      dateOfBirth: '2024-06-12',
      weight: 3.6,
      status: 'Sick',
      cageNumber: 'Iso-01',
      farmSection: 'Infirmary / Quarantine',
      purchaseDate: '2024-09-01',
      purchaseCost: 35,
      source: 'Homebred batch 1',
      photoUrl: 'https://images.unsplash.com/photo-1577975882846-431adc8c2009?w=500&auto=format&fit=crop&q=80',
      notes: 'Showing mild snuffles and watery eyes. Under antibiotic eye drops and isolation.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-106',
      earTag: 'ET-106',
      name: 'Snowdrop',
      gender: 'female',
      breed: 'New Zealand White',
      color: 'Albino White',
      dateOfBirth: '2024-07-22',
      weight: 3.4,
      status: 'Breeding',
      cageNumber: 'Doe-02',
      farmSection: 'Maternity Row 1',
      purchaseDate: '2024-08-15',
      purchaseCost: 40,
      source: 'Valley Farm Stock',
      photoUrl: 'https://images.unsplash.com/photo-1452857297128-d9c29adba80b?w=500&auto=format&fit=crop&q=80',
      notes: 'Scheduled for first breeding cycle next week with Buck Thunderbolt.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-107',
      earTag: 'ET-107',
      name: 'Caramel Kit #1',
      gender: 'female',
      breed: 'Californian / NZW Cross',
      color: 'Cream Buff',
      dateOfBirth: '2025-01-10',
      weight: 1.8,
      status: 'Active',
      cageNumber: 'Grower-04',
      farmSection: 'Grower Pen C',
      photoUrl: 'https://images.unsplash.com/photo-1506891536236-3a07892504b4?w=500&auto=format&fit=crop&q=80',
      notes: 'Healthy kit from Bella Luna litter. Good weight gain curve.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-108',
      earTag: 'ET-108',
      name: 'Rusty',
      gender: 'male',
      breed: 'New Zealand Red',
      color: 'Deep Auburn Red',
      dateOfBirth: '2024-02-14',
      weight: 4.6,
      status: 'Sold',
      cageNumber: 'Sold-Record',
      farmSection: 'Archived',
      purchaseDate: '2024-04-10',
      purchaseCost: 45,
      photoUrl: 'https://images.unsplash.com/photo-1589952283406-b53a7d1347e8?w=500&auto=format&fit=crop&q=80',
      notes: 'Sold to Green Valley Homestead for breeding line replacement.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ];
}

export function getSampleBreeding(farmId: string): Omit<BreedingRecord, 'id'>[] {
  return [
    {
      farmId,
      buckId: 'RT-101',
      buckName: 'Thunderbolt',
      doeId: 'RT-102',
      doeName: 'Bella Luna',
      breedingDate: '2026-09-10',
      expectedKindlingDate: '2026-10-11',
      breedingMethod: 'Natural',
      attemptsCount: 2,
      status: 'Active',
      notes: 'Doe accepted buck twice with fall-off observed. Abdominal palpation confirmed positive at 14 days.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      buckId: 'RT-104',
      buckName: 'Shadow',
      doeId: 'RT-103',
      doeName: 'Hazelnut',
      breedingDate: '2026-08-01',
      expectedKindlingDate: '2026-09-01',
      actualKindlingDate: '2026-09-02',
      breedingMethod: 'Natural',
      attemptsCount: 1,
      status: 'Kindled',
      notes: 'Successfully gave birth to 9 healthy kits. Excellent nest building.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ];
}

export function getSampleKindling(farmId: string): Omit<KindlingRecord, 'id'>[] {
  return [
    {
      farmId,
      doeId: 'RT-103',
      doeName: 'Hazelnut',
      buckId: 'RT-104',
      buckName: 'Shadow',
      kindlingDate: '2026-09-02',
      expectedDate: '2026-09-01',
      totalKits: 9,
      liveKits: 8,
      stillbornKits: 1,
      maleKits: 5,
      femaleKits: 3,
      nestCondition: 'Good',
      motherCondition: 'Excellent',
      notes: '8 vigorous kits nursing eagerly. Mother pulled generous amount of chest fur.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleHealth(farmId: string): Omit<HealthRecord, 'id'>[] {
  return [
    {
      farmId,
      rabbitId: 'RT-105',
      rabbitName: 'Clover',
      date: '2026-09-22',
      symptoms: 'Mild clear nasal discharge, sneezing, slight eye watering',
      diagnosis: 'Early pasteurellosis / snuffles irritation',
      treatment: 'Isolate in infirmary cage, warm clean bedding, probiotic in water',
      medicine: 'Oxytetracycline drops + Enrofloxacin oral',
      dosage: '0.2ml twice daily for 5 days',
      veterinarian: 'Dr. Sarah Jenkins (Avian & Exotic)',
      treatmentStartDate: '2026-09-22',
      treatmentEndDate: '2026-09-27',
      status: 'Under Treatment',
      cost: 28.5,
      notes: 'Appetite remains normal. Checked lung sounds; clear. Re-evaluate on day 5.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleVaccinations(farmId: string): Omit<VaccinationRecord, 'id'>[] {
  return [
    {
      farmId,
      rabbitId: 'RT-101',
      rabbitName: 'Thunderbolt',
      vaccineName: 'Filavac VHD / RHDV2 & Myxomatosis Combo',
      dateAdministered: '2026-04-10',
      nextVaccinationDate: '2026-10-10',
      dose: '0.5 ml subcutaneous',
      batchNumber: 'FLV-98214',
      veterinarian: 'Dr. Sarah Jenkins',
      cost: 18.0,
      notes: 'Annual booster. No localized swelling observed.',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitId: 'RT-102',
      rabbitName: 'Bella Luna',
      vaccineName: 'Filavac VHD / RHDV2',
      dateAdministered: '2026-05-15',
      nextVaccinationDate: '2026-11-15',
      dose: '0.5 ml subcutaneous',
      batchNumber: 'FLV-98214',
      veterinarian: 'Dr. Sarah Jenkins',
      cost: 18.0,
      notes: 'Safe for breeding doe.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleFeeding(farmId: string): Omit<FeedingRecord, 'id'>[] {
  return [
    {
      farmId,
      feedType: 'Pellets',
      quantity: 15,
      unit: 'kg',
      costPerUnit: 1.2,
      totalCost: 18.0,
      feedingDate: '2026-09-25',
      numberOfRabbits: 14,
      targetGroup: 'Main Herd & Breeders',
      notes: '16% protein commercial alfalfa pellets enriched with vitamins.',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      feedType: 'Hay',
      quantity: 5,
      unit: 'bundles',
      costPerUnit: 2.5,
      totalCost: 12.5,
      feedingDate: '2026-09-25',
      numberOfRabbits: 14,
      targetGroup: 'All Rabbits',
      notes: 'Fresh Timothy & Orchard grass blend for gut health and dental wear.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleExpenses(farmId: string): Omit<ExpenseRecord, 'id'>[] {
  return [
    {
      farmId,
      date: '2026-09-20',
      category: 'Feed',
      description: 'Purchased 4x 50kg bags of Premium Alfalfa Rabbit Pellets',
      amount: 145.0,
      paymentMethod: 'Bank Transfer',
      notes: 'Stocked feed store room for next 45 days.',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      date: '2026-09-18',
      category: 'Equipment',
      description: 'Automatic nipple waterer system upgrade & tubing',
      amount: 68.0,
      paymentMethod: 'Cash',
      notes: 'Reduced labor time for daily watering.',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      date: '2026-09-22',
      category: 'Medicine',
      description: 'Vet consultation & Antibiotic drops (Dr. Jenkins)',
      amount: 45.0,
      paymentMethod: 'Mobile Money',
      notes: 'Care package and preventive dewormer.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleInventory(farmId: string): Omit<InventoryItem, 'id'>[] {
  return [
    {
      farmId,
      name: '16% Breeder Rabbit Pellets',
      category: 'Feed',
      quantity: 120,
      unit: 'kg',
      purchasePrice: 1.15,
      supplier: 'AgriFeed Supplies Ltd',
      purchaseDate: '2026-09-15',
      expiryDate: '2027-03-15',
      minStockLevel: 40,
      location: 'Feed Room Bin 1',
      notes: 'High nutrient density feed for lactating does and fast grower kits.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      name: 'Timothy Grass Hay Bales',
      category: 'Feed',
      quantity: 12,
      unit: 'bundles',
      purchasePrice: 4.5,
      supplier: 'Green Valley Hay Farm',
      purchaseDate: '2026-09-01',
      expiryDate: '2027-08-01',
      minStockLevel: 5,
      location: 'Hay Shed A',
      notes: 'High fiber, green fragrant quality.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      name: 'Enrofloxacin 10% Oral Solution',
      category: 'Medicines',
      quantity: 2,
      unit: 'bottles',
      purchasePrice: 16.0,
      supplier: 'VetCare Pharmacy',
      purchaseDate: '2026-08-10',
      expiryDate: '2027-12-31',
      minStockLevel: 2,
      location: 'Medicine Cabinet Locked',
      notes: 'Broad spectrum respiratory treatment.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      name: 'Metal Nest Boxes with Liners',
      category: 'Equipment',
      quantity: 6,
      unit: 'pieces',
      purchasePrice: 14.0,
      supplier: 'Rabbitry Hardware Co',
      purchaseDate: '2026-07-20',
      minStockLevel: 3,
      location: 'Tool Shed Rack 2',
      notes: 'Sanitary metal nesting boxes with drainage holes.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      farmId,
      name: 'Multivitamin & Electrolyte Powder',
      category: 'Supplements',
      quantity: 3,
      unit: 'bottles',
      purchasePrice: 9.5,
      supplier: 'AgriVet Solutions',
      purchaseDate: '2026-08-25',
      expiryDate: '2028-01-01',
      minStockLevel: 2,
      location: 'Medicine Cabinet Top',
      notes: 'For stress relief during hot days or weaning.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ];
}

export function getSampleSales(farmId: string): Omit<SaleRecord, 'id'>[] {
  return [
    {
      farmId,
      rabbitId: 'RT-108',
      rabbitName: 'Rusty (NZ Red Buck)',
      rabbitCount: 1,
      saleType: 'Breeding Stock',
      customerName: 'Marcus Sterling',
      customerPhone: '+1 (555) 382-9012',
      saleDate: '2026-09-12',
      weightKg: 4.6,
      pricePerKg: 18.0,
      totalPrice: 85.0,
      paymentMethod: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Pedigreed red buck breeding stock sale with health booklet.',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      rabbitCount: 4,
      saleType: 'Meat Rabbit',
      customerName: 'Le Gourmet Bistro & Grill',
      customerPhone: '+1 (555) 721-4490',
      saleDate: '2026-09-24',
      weightKg: 11.2,
      pricePerKg: 12.5,
      totalPrice: 140.0,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      notes: 'Dressed live fryer weight lot. Weekly contract delivery.',
      createdAt: new Date().toISOString(),
    }
  ];
}

export function getSampleNotifications(farmId: string): Omit<FarmNotification, 'id'>[] {
  return [
    {
      farmId,
      title: 'Kindling Due Soon',
      message: 'Rabbit RT-102 (Bella Luna) is due for kindling in ~15 days. Prepare nest box with fresh hay by day 28.',
      category: 'Kindling',
      targetType: 'rabbit',
      targetId: 'RT-102',
      date: '2026-09-26',
      isRead: false,
      priority: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      title: 'Vaccination Booster Approaching',
      message: 'Stud buck RT-101 (Thunderbolt) Filavac booster is due on October 10.',
      category: 'Vaccination',
      targetType: 'rabbit',
      targetId: 'RT-101',
      date: '2026-09-24',
      isRead: false,
      priority: 'normal',
      createdAt: new Date().toISOString(),
    },
    {
      farmId,
      title: 'Health Follow-up Active',
      message: 'Clover (RT-105) daily antibiotic drop treatment day 4 in progress.',
      category: 'Health',
      targetType: 'rabbit',
      targetId: 'RT-105',
      date: '2026-09-25',
      isRead: true,
      priority: 'normal',
      createdAt: new Date().toISOString(),
    }
  ];
}
